[package]
name = "rust-tcp"
version = "0.1.0"
authors = ["Quang Luong <quangio@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tun = "0.5.0"
packet_crafter = "0.1.7"
